### ISSUE TITLE
docker-compose: multiple bridge networks

### ISSUE THREAD

**Issue by artfulrobot** [firehol/firehol#482]
I have two docker-compose projects running on the same host.

Each is configured as in #360, each with a docker-compose.yml `networks` part defining a network each, like
```yaml
networks:
  public:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.16.1.0/24
    driver_opts:
      com.docker.network.bridge.name: br_a
```

(the other one defines `subnet: 172.16.2.0/24` and bridge name `br_b`.)

And my firehol.conf file looks like this:

```
interface4 wlp170s0 lan2wifi src "192.168.1.0/24" 
	policy reject
	server ICMP accept
	client all accept

interface4 wlp170s0 world2wifi src not "${UNROUTABLE_IPS} 192.168.1.0/24"
	policy drop
	> protection strong
	client all accept

docker bridge br_a 172.16.1.0/24
docker_bridge br_b 172.16.2.0/24

interface4 "br_a,br_b" pnx_cont
  policy accept
```

One of these works fine (the 172.16.2.0 one). But the other one doesn't - seems all traffic within the network is dropped. Am I doing something wrong?
